[tool.poetry]
name = "test-clone-clean-code"
version = "0.1.0"
description = ""
authors = ["corvin <corvin.kraft@outlook.de>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
